stt003-05.otr
MonlamAI/STT003 pull request #1
Opened 2023-02-04 14:39 UTC by Lhundup22

ནང་ཆོས་ངོ་སྤྲོད་ཉིན་གཉིས་པའི་སྒྲ་ཐག་དང་པོ།

2023-02-11 06:50 UTC, Jamtsul requested changes
གཤམ་ལ་དཔེ་མཚོན་ཙམ་གྱིས་ནོར་བཅོས་འགའ་ཞུས་ཡོད་པ་འདིས་མཚོན་པ་ཙམ་ལས་གཙོ་བོ་དོ་བདག་སོ་སོས་གང་ཐུབ་ངང་ཞུབ་དཔྱོད་གནང་རོགས།
སྐར་ཆ་གཏན་འབེབ་ལས་བརྒལ་བ་04:48 ནས་05.04 ཅན་དང་། 07.49ནས་08.09ཅན་བཅས་བསྐྱར་དུ་གཏུབ་རོགས།   གཤམ་གྱི་སྣོན་རྟགས་སྔོན་གྱི་ཚིག་དག་མ་ཚིག་དང་། སྣོན་རྟགས་རྗེས་ཀྱི་ཚིག་དག་བཅོས་ཚིག་གམ་བསམ་ཚུལ་ཡིན་པའི་ཁུལ་ཡིན་ལགས།
1. ་་ཡིན་པ་དེ་ཤེས་པ་བྱ་རྒྱུ་སྟེ་པེ་གལ་ཆེན་པོ་རེད་ཞག +ཤེས་པར་བྱ་རྒྱུ་དེ་་་་་རེད་བཞག 
2. ་་་་ད་རྒྱ་གར་མཁས་པ་ཚོའི་ནང་ལས། +་་་་ནང་ལའང་།
3. ་་་བཞི་བརྒྱ་པའི་ནང་ནས་མུ་སྟེགས་པའི་་་་་བཀག་ཡོང་གིས་ཡོད་བ་རེད། དེ་འདྲའི་ཡིན་དུས། ཕ་ལམ། ་གྲུབ་མཐའིགཞུང་ལྟ་ཡིན་ +ནང་ལའང་མུ་སྟེགས་་་་་བཀག་ཡོང་གིན་་་་དེ་འདྲ་ཡིན་་་་་ཧ་ལམ་གྲུབ་མཐའི་གཞུང་འདྲ་བོ་རེད།
4. ་་་དབུ་མ་སྙིང་པོའི་ཡང་གྲུབ་མཐའ་དེ་གིའི་དེ། མང་པོ་ཞིག་གསུངས་ཡོད་བ་རེད། +་་སྙིང་པོར་ཡང་གྲུབ་མཐའ་དེའི་རིགས་མང་པོ་ཞིག་མར་གསུངས་ཡོད་པ་རེད།
5. མཐའི་གཞུང་རང་རེད་ཞག། +་་རེད་བཞག
6. ད་ཡེ་ཤུ་ད་ཁ་ཆེའི་དེ་ཚོའི་གྲས་་་+་་ཁ་ཆེ་དེ་ཚོའི་་་་
7. གྲུབ་མཐའ་དེ་གེ་ཆ་ཚང་ལོ་བཀོད་ནས། ཨ་ནི་སྒྲོ་འདོགས་བཅད་ནས་དོགས་དཔྱོད་བྱས་བྱས། +གྲུབ་མཐའ་ཁག་དེ་གས་དེ་ཆ་ཚང་མར་བཀོད་ནས། ཨེ་ནས་་་་་་་་་དོགས་དཔྱོད་བྱས་ཀྱིས།
8. ་་སངས་རྒྱས་ཀྱི་གྲུབ་མཐའི་ཁྱད་པར་དེ་གེ་གསུངས་ཡོང་གི་འདུག་ག ཟེ་འ་དེ་གེ་རྒྱ་གར་་་་ +སངས་རྒྱས་པའི་་་་་དེ་གས་དེ་་་་་ཡོང་གིན་་་་ཟའ་ད་དེ་་་་
9. ་་་མང་པོ་ཞིག་ཡོད་པོ་ཅེས་དེ་གེ་དག་གི་ནང་ལོག་ནས་ནང་ཆོས་གསོན་དགོས་ཀྱི་ཡོད་པ་རེད། དེ་ནང་ནས +་་་ཡོད་པ་བྱས། དེ་གས་དེའིི་ནང་་་་་་་་དགོས་ཀི་ཡོད་པ་རེད། དེའི་ནང་ནས་
10. ་་དགོས་ཀྱིཡོད་པ་ཡིན་དུས་ཙང་ནས། གྲུབ་མཐའ་མི་མཐུན་པ་དེ་གེ་དེ་ཚང་མ་ལོ་ཡ་བཀོད་ནས། ཨ་ནེ་བརྡར་ཤ་བཅད་ཅེས་འགྲོ་སྡོད་ཀྱི་འདུག་ག +་་དགོས་ཀི་ཡོད་་་་་དུས་ཙ་ནས། ་་་དེ་གས་དེ་ཚང་མ་ལོ་ཡར་བཀོད་་་་ཨེ་ནས་་་་བཅད་བྱས་་་་བསྡད་ཀིན་་་
11. ་་ཨ་ནེ  འུང ་ +ཨེ་ནས། འ་་་
12. ཨ་ནེ་ཕ་ལམ་ད་ཅིག་བོད་མི་་་་། ་་་་་ཆགས་འགྲོ་གི་ཡོད་བ་རེད།་་་་སྐད་ཆ་བྱུང་བ་གནང་བཞིན་་་།+ཨེ་ནས་ཧ་ལམ་་་། །ཆགས་བསྡད་ཀི་ཡོད་་་། ་་་བྱུང་བ་ནང་བཞིན་་་་
13. རྒྱ་ཆེན་པོ་ཡོད་བ་རེད་ཡོད་བ་རེད་དེ། ་ཡིན་ན་ལས་ནང་ཆོས་་་་་ +་་་ཡོད་པ་རེད། ཡོད་པ་རེད་དེ། ཡིན་ནའང་ནང་་་་་།
14. ་་་་་བཾ་ཧོ་ཞེས་པ་ ཧེ་ཧེ་་དེ་རེད། ནང་ཆོས་ནང་ལེས་་་བོན་གྱི། +་་ཟེར་ཡ་དེ་རེད་ཧེ་ཧེ། ་་་་ནང་ལའང་བོན་གི།
15.  ་་་་དཔེ་ཆ་དེ་ད། ཨ་ནེ་་ང་ཚོས་ནམ་རྒྱུན་ད་ཅིག ཐུགས་དམ་གྱི་གཙོ་བོ་ར་བྱས་ཡ་གཡང་སྒྲུབ་བྱས་ཡ་ཟེར་ཡའི་སྲོལ་འདྲ་བོའི་དེ་ཚེ་གྲས་དེ། +་་་དེ་རེད། ཨེ་ནས་ང་ཚོས་་་་་་་་་གཙོ་བོ་འདྲ་བོ་བྱེད་ཡ། གཡང་སྒྲུབ་བྱེད་ཡ་ཟེར་ཡ་དེ་ཚོའི་གྲས་དེ། ཞེས་པ་ལྟ་བུའི་དག་ནོར་དང་ཆད་ལྷག་དུ་མ་གཤམ་དུའང་འདུག་ཀྱང་ཆ་ཚང་ཞིག་བཅོས་ཐབས་མ་བྱུང་བས་དེ་ག་ནས་གོང་ཞུས་ལྟར་དོ་ནན་གྱིས་སོ་སོས་བསྐྱར་ཞུབ་གནང་རོགས།

2023-03-15 15:51 UTC, Jamtsul requested changes
stt003-07འགོ་ནས་བཅོས་ཡོད།

1. ནང་ལོག་+་ལོགས་(5)
2. ་ཟེར་བཅས་+་ཟེར་བྱས་ནས་
3. ་ཏིང་ངེས་+་ངེ་
4. བསགས་མཁན་+་བསགས་ངེ་
5. ་དེས་ནས་+་དེ་
6. རྒྱབ་ཡོང་+་བརྒྱབ་
7. ་ཡིན་རེད།+་ཡིན་པ་རེད།
8. ་འདས་ཀི་མདོའི་+་ཀིས་
9. ་ཏུ་རྟོགས་+་རྟོག་
10. ་ངང་ཞི་+་ངང་དུ་ཞི་
11. ་སུས་གཅིག་+་སུ་
12. ་དེ་དབང་གིས་+་དེའི་
13. ་ལག་གི་+་ལག་བཅུ་གཉིས་ཀི་
14. ་ཟོར་འདྲ་+་ཟོལ་(11)
15. ་ཚགས་སྒང་+་ཚགས་པོའི་སྒང་
16. ་བྱེད་ཐབས་+སྒྲུབ་ཀྱི་ཐབས་
17. ཏོག་སུ་+་ཏོག་སི/ཏོག་ཙི/ཏོག་ཟི་
18. ་ཆུང་ཐོག་+་ཆུང་གི་ཐོག་
19. ་སུ་བཅས་+་ཟེར་བྱས་
20. ་སྐད་གཙོ་+་སྐད་ལ་གཙོ་
21. ་ཞེས་ནས་འདི་ཡང་+་ཟེར་བྱས་ནས་འདི་ནས་ཡ་
22. ་བསམ་པ་དང་+་བསམ་པ་གིས་
23. ་དབུ་པ་+་མ་
24. ་ང་ཚོའི་དེ་བཤད་+་ཚོས་
25. དེ་ཁཽ་ན་+་ཁོ་
26. ་པ་བཞག་གི་ཡོདཔ་+་པ་ཟེར་བཞག་གི་ཡོད་པ་
27. ་གི་སྐྱག་རྫུན་+་གིས་
28. ་རྡོལ་སོང་+་བརྡོལ་
29. ་ལ་སྐྱོན་+་ལ་ཚུར་སྐྱོན་
30. འདུས་སེ་+་འདུག་(10)
31. ་ཁོས་ཕུང་+་འཕུང་
32. ་ཕན་གིས་+་གི་(4)
33. ་རྒྱུ་མ་+་སྒྱུ་
34. ག་ཙུག་+་ག་ཚད་
35. ཚོད་ཀྱི།+་ཀྱིས།
36. ་ཞེས་ནས་ཟེར་+་བྱས་ནས་ཟེར་
37. ་ཞེས་ནས་ལབ་+་ཟེར་ནས་ལབ་
38. ་ཞུལ་+་བྱུགས་
39. ་སྐྱེད་བྱ་+་བསྐྱེད་
40. ངོ་ལ་+་ངོ་བོ་ལ་
41. ་འདུས་སེ།+་འདུག་སེ།
42. ་བཅད་ཡོང་+་དཔྱད་
43. ་ཟེར་བསྡད་ཡ་བསྡད་ཡ་གི་ ང་ངོ་རྡོག་+་ཟེར་བསྡད་ཡ་གི། ང་ངོ་ཐོག་
44. ་གང་དུ་སྟོང་+་དེ་
45. ་བརྟེན་བཏགས་+་བརྟེན་ནས་བཏགས་
46. ་བ་གིས་+་བ་དེ་གིས་
47. ་ག་མཁེན་+་ག མཁྱེན་
48. ་འདི་བཤད་ནས།+་འདི་ཤེས་ནས།
49. སྨད་བྱུང་+་རྨད་(2)
50. ་ཕྱེས+་ཕྱེ་(9)
51. ་ཞི་ཞི་ཞི་བའི་ཚེ་ཉེར་+་ཞི་ཞིང་ཞི་བའི་མཚན་ཉིད་
52. ཏོག་སེ་+་ཏོག་སི་/ཏོག་ཙི/ཏོག་ཟི་(4)
53. ་མི་རྐྱང་+་མིང་
54. ་ཅི་ལོག་པར།+་ཅི་མ་ལོག་པར།
55. སྐབས་འགྲོ།+སྐྱབས་
56. ་འབྱུང་བསམ་+་འབྱུང་གི་བསམ་
57. ་ཀ་ལ་གནོད་པ་ཆགས་ཡོང་+་ཆ་ལ་འབྲེལ་བ་ཆགས་ཡོད་
58. ་སྲོག་ལ་སྐྱོབ་ཡ་གིས་+་སྲོག་སྐྱོབ་ཡ་གི་
59. ་ཐུགས་རུས་+་ཐེའུ་རེས་
60. ་སྐྱོབ་ཀི་དཔག་པའི་+་སྐྱོབ་པ་གི་
61. ་ཡོན་གིས་+་ཡོང་གིན་
62. ་འདྲ་བྱས་+་འདྲ་བོ་བྱེད་
63. ་གཏམ་རིང་+་གཏིང་
64. ་རང་ཚོའི་དགེ་+་ཚོས་
65. ནའ་+་ནའི་
66. ་རྗེ་གདུལ་+་རྗེ་ཐེག་པའི་གདུལ་
67. ་བརྒྱ་ཐག་+་བརྒྱ་ཐམས་པ་ཐག་
68. ནང་སོང་+་ངན་སོང་
69. ་ག་གས་+་ག་གེ་
70. དབང་འདུས་+་སྡུད་
71. ་རྗེ་བསམ་པ་+་རྗེའི་
72. ཞེ་བོས་+་བོ་(5)
73. ་གྲས་་བཞག་+་ཆག་
74. ་པའི་འཚེ་བ་བྱས་སོང་ཅེས་+་པས་འཚེ་བ་བྱས་སོང་བྱས་
75. ང་ཚོའི་འཚེ་བ་+་ཚོས་
76. ་ཡོངས་ཀིས་རེ་བསྐུར་གནང་བ་+་ཡོངས་ལ་རེ་བསྐུུལ་བྱས་པ་
77. ་ད་དཔེ་+་ད་ཕ་གིར་
78. ་བསྐུར་+་བསྐུལ་(3)
79. ་ཡིག་གེ་+་ཡི་གེ་
80. ལྟ་རོགས་ཀྱིས་ཞེས་+བལྟ་རོགས་ཀྱིས་ཟེར་བྱས་
81. ་ཡོད་བྱས་+་ཡོད་ཟེར་བྱས་
82. ་ཡིན་ན་བཏང་གིས་ཡོད་མ་+་ཡིན་ནའང་གཏང་གི་ཡོད་མ་
83. ་ཚེ་པ་+་ཚེས་
84. stt003-07ཡོངས་རྫོགས་བཅོས་ཡོད།

2023-03-16 11:33 UTC, Jamtsul requested changes
སྐར་མ་08:56ནས་བཅོས།
* མཁས་པའི་གྲུབ་མཐའ་མཛད་ཞག་པ་དེ་ཚོ་གཞི་ལ་བཞག་ཞག་པས་+མཁས་པས་གྲུབ་མཐའ་མཛད་བཞག་པ་དེ་ཚོ་གཞི་ལ་བཞག་པའི་
* སྤྱི་གཏང་+སྤྱིར་བཏང་
* ས་དགེ་རྙིང་གསུམ་རེ་སུ་+ས་དགེ་བཀའ་རྙིང་རིས་སུ་
* ་གསུང་པ་ནང་ལོག་+གསུང་གི་
* ལོག་རྟོག་རྣམ་ཤེས་གསུང་ཡ་འདྲ་པོ།་+བློ་ལྡོག་རྣམ་བཞི་གསུངས་པ་འདྲ་བོ།
* ་ད་ག་གནང་བཞིན་གིའི་ཨ་ནེ་+དེ་ག་ནང་བཞིན་གི་ཨེ་ནས་
* སྐྱེ་བུ་གསུམ་གྱི་ཐོག་ནས་ད་ཁྲིད་གཏང་+སྐྱེས་བུ་གསུམ་གྱི་ལམ་རིམ་གི་ཐོག་ནས་འཁྲིད་སྟངས།
* ་ང་ཚོའོ་གཙོ་བོ་བྱས་ནས་ཁྲིད་གནང་གིས་+ང་ཚོས་གཙོ་བོ་བྱས་ནས་འཁྲིད་གནང་གི་
* ཡིན་གཞི་བཞག+ཡིན་ཤག་ཤག
* སྟོས་ཟིན་+བལྟས་ཟིན་
* རྒྱུས་ཡོད་སྡོད་པ+རྒྱུས་ཡོད་བསྡད་པ།
* དེ་འདྲའི་ཅིག་གཞི་བཞག་བྱས་བྱས་ཕར་ཆེར་གསུང་པས་+དེ་འདྲ་ཞིག་གཞིར་བཞག་བྱེད་བྱས་ཕལ་ཆེར་གསུངས་པའི་
* མཐོང་མོ་+མཐོང་ཆེན་མོ་
* ཁེག་པོ་བྱས་གིའི་འདུག་ག་ ཅེས་ཙང་དབུ་ཕར་གྱི་གཞུང་སྟོས་ཟིན་ཉའི་ཞིག+ཁག་པོ་བྱེད་ཀི་འདུག་ག བྱས་ཙང་དབུ་ཕར་གྱི་གཞུང་བལྟས་ཟིན་ངེ་ཞིག
* དེ་འདྲའི་ཞིག་+དེ་འདྲ་ཞིག་
* གསུང་བཞག་པ་+གསུངས་བཞག་པ་
* ་སྤྱི་གཏང་+སྤྱིར་བཏང་
* ནང་པ་ཡིན་བཞག་+ནང་པ་ཡིན་ཤག་
* རྩལ་དཔྱོད་མེད་ན་ཡའི+རྩར་བཅད་མེད་ན་ཡང་།/རྩད་བཅད་མེད་ན་ཡང་།
* ད་སྔོན་ལ་་དང་པོ་གཞི་བཞག་རང་ཅེས་ནས་+ད་ནང་པ་གཞིར་བཞག་རང་བྱས་ནས་
* གཞི་བཞག་ར་བྱས་ནས། ཨ་ནེ+གཞིར་བཞག་བྱེད་བྱས་ནས་ཨེ་ནས།
* གཞི་ནས་བཤེས་གཉེན་རྟེན་ཚུལ་ནས་ཅེས་མ་ཁྲིད་ཡོང་ཡ་འདྲ་བོ་དེ་འདྲའི་+མ་རྩ་བཤེས་གཉེན་བརྟེན་ཚུལ་ནས་ཀྱིས་མར་འཁྲིད་ཡོང་ཡ་འདྲ་བོ་དེ་འདྲ་
* གནས་སྟེང་+གནས་སྟངས་
* ལ་སྡོད་ཡོད་བ་+ལ་བསྡད་ཡོད་པ་
* སླེབ་སྡོད་ཡོད་བ་+སླེབས་བསྡད་ཡོད་པ་
* སླེབ་པ་ཙམ་དུ་མ་ཞད་པས+སླེབས་པ་ཙམ་དུ་མ་ཟད་པར་
* སླེབ་སྡོད་ཡོད་བ་+སླེབས་བསྡད་ཡོད་པ་
* འདི་དགང་གི་ཆོས་རྒྱུད་+འདིའི་སྒང་གི་ཆོས་བརྒྱུད་
* ་དེང་སེང་+དེང་སང་
* ་གཞུང་ལུགས་ད་+་གཞུང་ལུགས་དང་
* རིག་ལམ་+རིགས་ལམ་
* དངོས་བོའོ་+དངོས་པོའི་
* ་ཆགས་སྡོད་ཡོད་བ་+་ཆགས་བསྡད་ཡོད་པ་
* དཔེ་གལ་ཆེན་པོ་རེད་ང་ཚོ་+དཔེ་གལ་ཆེན་པོ་རེད། ང་ཚོ་
* ་ང་ཚོ་ཡར་རྒྱས་འགྲོ་ཡ་ཆེན་པོ་གིའི་ཡར་རྒྱས་+ང་ཚོ་ཡར་རྒྱས་འགྲོ་ཡ། ཕྱིའི་དངོས་པོ་ཡར་རྒྱས་
* ་འགྲོ་གིའི་ཡོད་བརེད་།+་འགྲོ་གི་ཡོད་པ་རེད།
* ་ཡིན་པས།+་ཡིན་པར།
* ཕར་སློད་སློད་ཡོང་ཡ། བསམ་བློ་་སློད་སློད་དེ་།+ཕར་ལྷོད་ལྷོད་ཡོང་ཡ། བསམ་བློ་ལྷོད་ལྷོད་དེས།
* དག་ག་གནང་བཞིན་གིའི།+དེ་ག་ནང་བཞིན་གིས།
* ་ཟ་ང་་ཟིང་ངེ་ཡོངས་སྡོད་ཡ་+་ཟ་ངེེ་ཟིང་ངེ་ཡོང་བསྡད་ཡ་
* ་རྒྱག་ཉའི་ཡོངས་བསྡད་ཉའི་+་རྒྱག་ངེ་ཡོང་བསྡད་ངེ་
* ་རྐྱེན་གིའི་མ་འདེང་+་རྐྱེན་གིས་མ་འདངས་
* ་སླེབ་ཡོངས་+་སླེབ་ཡོང་
* ་བློའི་སྟངས་+་བློའི་སྟེང་
* ་སླེབ་ཡོང་གིའི་+་སླེབ་ཡོང་གིན་
* འུང དེ་གིའི་དེ་གང་གང་་འུང +འོ་ད་དེའི་སྒང་ལ་
* འ་ད་པར་དུ་+འ་ད་བར་དུ་
* ་ཕྲག་ཅིག་གཉིས་འདིའི་རང་ལ་+ཕྲག་གཅིག་གཉིས་འདིའི་རིང་ལ་
* སྩལ་དཔྱོད་མ་བྱས་བ་+རྩད་གཅོད་མ་བྱས་པ་
* ་ཕ་གིའི་།+་ཕ་གིར།
* ་སྔ་རབ་གིའི་+གནའ་རབས་ཀི་
* ་ཆེན་ཡོད་+་ཆེན་པོ་ཡོད་
*

2023-03-18 11:22 UTC, Jamtsul requested changes
སྐར་མ་12:06ནས་བཅོས།
* ་རྣམ་བཞག་མང་བ་+རྣམ་གཞག་མང་ང་
* དེ་འདྲའི་+དེ་འདྲ་
* ་གར་གིའི་ ད་ནང་ཆོས་ཐེ་བའི་རྒྱ་གར་གིའི་ད་ལྟ་གྲུབ་རྙིང་པ་+གར་གི་ད་ནང་ཆོས་ཐེ་བའི་རྒྱ་གར་གི་ལྟ་གྲུབ་རྙིང་པ་
* ་ཡོད་བ་རེད་བ།+ཡོད་པ་རེད་པ།
* ་རགས་གིའི་+་རགས་ཀི་
* ་ཐེ་པའི།+་ཐེ་བའི།
* ་སྒོམ་གིའི་རྣམ་བཞག་བཞད་+སྒོམ་གི་རྣམ་བཞག་བཤད་
* དེ་ནང་ཚན་+དེའི་ནང་ཚན་
* ་སངས་རྒྱས་ཀྱི་+་སངས་རྒྱས་པའི་
* ་དེ་ཐོག་ལ་དམིགས་གསལ་གིའི་+་དེའི་ཐོག་ལ་དམིགས་བསལ་གི་
* ་རྟེན་ནས་འབྱུང་བ་་་་་རྟེན་ནས་+་བརྟེན་ནས་འབྱུང་བ། བརྟེན་ནས་
* ་དེ་འདྲའི་ཅིག་གིའི་+་དེ་འདྲ་ཞིག་གི་
*  ་ང་ཚོའི་ནང་པ་+་ང་ཚོ་ནང་པ་
* ་ཆོས་པ་ཚོའི་+་ཚོས་
* སངས་རྒྱས་བའི་+་པའི་
* ་དེ་བྱས་གིའི་+་བྱེད་ཀི་
* ་དག་ག་སུ་གིའི་+དེ་ག་ཟིག་གི་
* ་ཆེན་པོ་ད།+་ཆེན་པོ་དང་།
* ་ཁེགས་+་ཁག་
* རེ་བ།+རེད་པ།
* རང་ཉིད་ཀྱི་ཉམས་+་ཀྱིས་
* ་རྩིས་བ་+བརྩིས་པ་
* ་བཏུས་ཡ་+་བཏུལ་
* ་གཏོག་+་གཏོགས་
* ་ནའི+་ནའང་།
* སྤྱི་གཏང་+སྤྱིར་བཏང་
* ་ང་ཚོའི་བོད་པའི་+་ཚོ་
* ་ཞིག་དྲེ་ནས།+་ཞིག་བསྲེས་ནས་
* ག་རེ་སེར་ན།+ག་རེད་ཟེར་ན།
* ་ཡིན་རླུང་+་ཡིན་ན་རླུང་
* ་སྡོད་ཉའི་+བསྡད་ངེ་
* ་ལུས་ཟེ་+་ལུས་ཤིག་
* ཁོ་དེ་ལ་ཞིག་པ་ཅིག་གིའི།+་གཞིགས་པ་ཞིག་གིས་
* ་པས་སྟེང་ནང་+་པའི་ཐོག་ནས་
* ་གིའི་མ་གཏོག+་གི་མ་གཏོགས།
* ་ཟེར་ཡའི་དེ་ཡིའི།+་ཟེར་ངེ་དེ་ཡང་།
* ་དེ་འདྲའི་གིའི་+་དེ་འདྲ་ཡི་
* ་ཡོངས་བསྡད་+་ཡོང་
* ་བྱས་ཡ་+་བྱེད་
* མ་སོང་ནའི་དཔེ། སྣ་ཁ་+་མ་སོང་ན། དཔེ་སྣ་ཁ་
* ་བཏང་སྟེང་ནས་ཤེས་+་གཏོང་སྟངས་ཤེས་
* ་ཤུགས་ཆེན་ཡ་ཡོང་+་ཤུགས་ཆེ་རུ་ཡོང་
* ་གཅིག་པོ་གིའི།+་གིས་
* ་འདྲ་བོ། གཅིག་པོའི་གིའི་+་འདྲ་བོ་གཅིག་པོ་གི་
* ས་ཆོད་ཆེ་ཡ་+་ས་ཆོད་ཆེ་བ་
* དག་ག་གནང་བཞིན་གིའི་+དེ་ག་ནང་བཞིན་གི་
* ་ཚོགས་གིའི་+་ཚོགས་ཀི་
* ཤེས་ཚད་རེ་བ།+་ཤེས་ཚད་འདྲ་བོ།
* ་གིའི་ཐོག་ལ་ཡིན་ནའི།+་གི་ཐོག་ལ་ཡིན་ནའང་།
* ་ཆགས་བཞག་+་ཆག་བཞག་/་ཆ་བཞག་
* དབུས་པའི་བློ་གསལ་གིའི་+དབུས་པ་བློ་གསལ་གི་
* ་ཚད་གིའི་+་ཀི་
* ་གྲུབ་མཐའ་མཛད་ཡོད་བ་+་གྲུབ་མཐའ་མཛོད་ཡོད་པ་
* ་རྒྱ་མཚོའི་དེ་ཚོའི་+་མཚོ་དེ་ཚོས་
* ་ཡོད་སྡོད་ཉའི་ཅིག+་བསྡད་ངེ་ཞིག
* ཅེས་ཙང་ང་ཚོ་+བྱས་ཙང་ང་ཚོས་
* ་ཆགས་བཞག་ནེ་ལའི།+་ཆག་བཞག་/ཆ་བཞག་ནའང་།
* ་གིའི་ཁྱད་པར་དེ་ཚོའོ་+་གི་ཁྱད་པར་དེ་ཚོའི་
* ་ཤེས་བའི་+་ཤེས་པའི་
* ཨ་ནེ་སོ་སོའི་ཉམས་+ཨེ་ནས་སོ་སོས་ཉམས་
* ་ཡིན་རེད།+་ཡིན་ནའང་རེད།
* ་ཞིག་འདོན་ཉི་དྲོ་+་ཅིག་བརྒྱག་སྙིང་འདོད་སོང་།
* ་འདུན་ཅིག་འདོན་ཉི་+་འདུན་གཅིག་འདོན་སྙིང་
* ་ང་ཚོའོ་སློབ་སྦྱོང་+་ཚོས་
* འབོད་སྐུར་+་སྐུལ་
* ངས་འདི་བཤད་པ་ཙམ་མ་ཡིན་པའི།+ངས་འདིར་བཤད་པ་ཙམ་མ་ཡིན་པར།
* ་སློབ་གྲ་+་གྲྭ་
* ་ཡའི་གཅིག་ཕྱིན་ཅེས།+་ཡང་གཅིག་ཕྱིན་བྱས།
* དེ་གིའི་བུ་གུ་ཚོ་འགྲེལ་བཞད་རྒྱག་ཡ་དེ་འདྲའི་བྱས་བ་+དེ་གའི་བུ་གུ་ཚོར་འགྲེལ་བཤད་བརྒྱབ་ཡ་དེ་འདྲ་བྱས་པ་
* ཁྱེད་རང་ཚོའི་དུས་དུས་ལ་+་ཚོར་
* གང་ལྟར་ཅིག་+་གང་ལྟར་ཀྱང་
* གསར་པ་སླེབ་བསྡད་ཡ་+་སླེབས་
* ་ད་ཞེ་ལབ་པ་གནང་བཞིན་+་ད་ཅི་ལབ་པ་ནང་བཞིན་
* ད་ཞེ་ཡང་+་ད་ཅི་
* ཚུགས་ཉའི་དེ།+་ཚུགས་ངེ་དེ་
* ་ནཱ་ལེན་གྲ་+་ནཱ་ལེནྡྲ་
* ་ཀླུ་སྒྲུབ་གིའི་+་སྒྲུབ་ཀི་
* ་སྟོང་དེ་+་སྟོང་གི་དེ་
* ་ཉིད་ད་ཟུང་+་ཉིད་དང་ཟུང་
* ་བཟུང་ཉའི་གིའི། བཟུང་ཉའི་+་གསུངས་ངེ་གི གསུངས་ངེ་
* ་ལྟ་བ་ད་འདྲེས་+་ལྟ་བ་དང་འདྲེས་
* དེ་འདྲའི་གིའི་སེམས་ཙམ་པའི་ལྟ་བ་ད་འདྲེས་ནས།+དེ་འདྲ་གི་སེམས་ཙམ་པའི་ལྟ་བ་དང་འབྲེལ་ནས་
* ཕར་ཆེར་སྲོལ་དོད་མཁན་དེ་ཕར་ཆེར་ཁོང་མུན་དྲོ།+ཕལ་ཆེར་སྲོལ་བཏོད་མཁན་དེ་ཕལ་ཆེར་ཁོང་མིན་འགྲོ།
* ་གྲོ་སྡེ་ག་འདྲ་ཡིན་དྲོ།+གྲོལ་སྡེ་ག་འདྲ་ཡིན་འགྲོ།
* ་རྗེས་གོ་+་གཞུག་གུ་
* ་གཅིག་ཙི་+་གཅིག་ཅིག་
* ་བརྒྱ་སུ་+་བརྒྱ་ཞིག་
* ་ག་རེ་ཟེ།+ག་རེ་ཟེར།
* ཁོ་གིའི་+ཁོང་གི་
* ་བརྒྱ་ཟེ་+་བརྒྱ་ཞིག་
* ་བཅུ་ཟེ་+་བཅུ་ཞིག་
* ་ཡོད་བ་རེད་ཟེ+་ཡོད་པ་རེད་ཟེར།
* ་ཚོའི་དགུ་བཅུའི་དགང་ལ་ཀླལ་ཀོར་ཞིག་བརྒྱ་+་ཚོས་དགུ་བཅུའི་སྒང་ལ་ཀླད་ཀོར་ཞིག་བརྒྱབ་
* ་དོ་སུ་+་འདུག་སེ་

2023-03-20 11:43 UTC, Jamtsul requested changes
སྐར་མ་19:10་ནས་བཅོས་ཡོད།
* གསར་པོ་+གསལ་བོ་
* གང་ལྟར་དེ་ཡོངས་+གང་ལྟར་ད་ཡོངས་
* ་ལྡན་གྱི་མདོ་སྡེ་+་གྱིས་
* ་ཕྱི་སུ་+་ཕྱིས་སུ་
* ་གསུང་སྟེང་+་སྟངས་
* ་འོས་བསམ་ཅེས། ཕར་ཆེར་ཆགས་གིའི་ཡོད་བ་རེད+་འོས་པའི་ཟོར་འདྲ་བོ་ཞིག་ཕལ་ཆེར་ཆགས་ཀི་ཡོད་པ་རེད།
* ད་ལྟ་ངས་དེ་+གང་ལྟར་ངས་དེ་
* ་ཕུད་ཟེ་ཡིན་པ་མ་ཟད་+་ཕུད་ཅིག་ཡིན་པ་ཙམ་དུ་མ་ཟད་
* ་འཛིན་ཉའི་གིའི་ནང་ལོག་ལའི+་འཛིན་ངེ་གི་ནང་ལོག་ལའང་།
* དམིགས་གསལ་གིའི་ཡང་སྲོལ་གསར་བ་ཞིག་བཏོད་ཉའི་ཟེ་ཆགས་བསྡད་ཡོད་བ་+དམིགས་བསལ་གིས་ཡང་སྲོལ་གསར་པ་ཞིག་བཏོད་ངེ་ཞིག་ཆགས་བསྡད་ཡོད་པ་
* ་འབྲེང་ཉའི་+་འབྲང་ངེ་
* རེ་བ།+རེད་པ།
* ་བཤེས་ཞིག་གི་ནང་+་གིས་
* ཁོ་རང་གིའི་བསམ་བློ་བཏང་ཁོ་རང་གིའི་དགོངས་པ་བཞེས་ཅེས་སྲོལ་གསལ་བ་ཞིག་བཏོད་གོ་བྱུང་ན།+ཁོ་རང་གིས་བསམ་བློ་བཏང་། ཁོ་རང་གིས་དགོངས་པ་བཞེས་བྱས་སྲོལ་གསར་པ་ཞིག་བཏོད་དགོས་བྱུང་ན།
* ་པོ་ཟོར་འདྲ་བོ་ཞིག་གིའི་སྲོལ་གསལ་བ་+་པོ་ཆེའི་ཟོར་འདྲ་བོ་ཞིག་གིས་སྲོལ་གསར་པ་
* ་དགོས་བ་རེད་མ་གཏོག་དག་ག་སུ་ཞིག་ཡོང་གིའི་མ་རེ་བ+དགོས་པ་རེད་མ་གཏོགས། ད་ག་ཞིག་གིས་འབྱེད་ཐུབ་ཀི་མ་རེད་པ།
* ཟེ་ཨ་དེ་འདྲའི་དྲན་གིའི། ཅིས་ཙང་+བྱས་ཙང་ངས་དེ་འདྲ་ཞིག་དྲན་གི བྱས་ཙང་
* ་ཞི་བོའི་ཅིག་+ཞེ་བོ་ཞིག་
* ་པའི་ང་ཚོའི་+་པའི་དཔེ་ཆ་ང་ཚོས་
* དག་ག་གནང་བཞིན་གིའི།+ད་ག་ནང་བཞིན་གི
* ་ཆགས་བཞག་+་ཆག་བཞག་/ཆ་བཞག་
* ཀརྨ་ལ་ཤའི་ལ་ཡིན་པ་རེད།་ཀརྨ་ལ་ཤའི། ད་ཁོང་གིའི་+་ཀ་མ་ལ་ཤཱི་ལ་ཡིན་པ་རེད། ཀ་མ་ལ་ཤཱིས། ད་ཁོང་གིས་
* ་བར་གསམ་+་གསུམ་
* ་དེ་གིའི་དེ་+་དེ་གས་དེ་
* ་ལས་མཁས་+་ལས་པའི་མཁས་
* ་ཅེས་ཙང་ང་ཚོ་དེ་+བྱས་ཙང་ང་ཚོ་དེའི་
* ་ཁྲི་སྲུང་སྡེ་བཙན་གྱི་གདན་ཞུས་སྣང་བོད་+ཁྲི་སྲོང་ལྡེའུ་/ལྡེ་བཙན་གྱིས་གདན་ཞུས་གནང་། ཨེ་ནས་བོད་
* ་བསྡད་ཉིའི་ཅིག་གི རྒྱ་གར་རང་མཁས་+་བསྡད་ངེ་ཅིག རྒྱ་གར་མཁས་
* ་རེ་བོང་གུ་+་རེར་
* ་གནང་ཅེས་+་གནང་བྱས་
* ་སྐབས་རེ་+་རེར་
* ་གནང་སྐབས་རེ་+་གནང་། སྐབས་རེར་
* ་དེ་འདྲའི་ཆིབ་ཅེས་+་དེ་འདྲར་བཅིབས་བྱས་
* ་ཉའི་དེ།+་ངེ་དེ།
* ་དེ་ཕེབས་+་དེར་ཕེབས་
* ་བསིལ་ཅེས།+་བསིལ་གྱིས་
* ་དོའི་སུ་+་འདུག་སེ་
* ་དེ་འདྲའི་གིའི་+་འདྲ་གི་
* ་ང་ཚོ་སྲོལ་+་ཚོར་
* ་ཉིའི་ཟེ་ཡིན་དུས་+་ངེ་ཞིག་
* ་གནང་བཞིན་+་ནང་
* ་ཟེར་གིའི་འདུག་+་ཟེར་གིན་
* ་འབྲེལ་བྱས་ཡ་+་བྱེད་ཡ་
* ་དེ་འདྲའི་ཡིན་དུ+་དེ་འདྲ་ཡིན་དུས།
* ་ནང་པ་ཚོའི+་ཚོས།
* ་ཕྱོགས་ནས་+་ཕྱོགས་གཅིག་ནས་
* ་རིག་ལམ་སློབ་ཡ་+་རིགས་
* དེ་ན་དེ་ཡིན་+་དེ་ཡིན་ན་དེ་ཡིན་
* ་་གིའི་རེད་ཟེ་ཨ་ནེ་+་གི་རེད་ཟེར་ཨེ་ནས་
* ་གི་རིད།+་ཀི་རེད་
* ་ཁྱབ་གིའི་མ་རེ་ཟེར་+་ཁྱབ་ཀི་མ་རེད་ཟེར་
* ་རྩི་ཡ་ད།+་དེ་
* ་བཀོད་ཁོ་རང་།+་བཀོད་ཡ་ཁོ་རང་
* ་ཅིས་ནས་ལབ་+་བྱས་ནས་ལབ་
* ་འདི་ཞིག་ཤཻས་དགོས་གིའི་+་འདི་གཅིག་ཤེས་དགོས་ཀི་
* ་་ཤེས་ན་རྒྱུ་མཚན་+་དགེ་མཚན་
* ཡང་ཁོ་ང་ཚོ་འདི་ར་བྱས་གིའི་ག +་ཡང་ཁོ་ང་ཚོས་འདི་འདྲ་བོ་བྱེད་ཀིན་འདུག་ག
* སྤོབས་པ་ར་བྱས་གིའི་འདུག་ག་+སྤོབས་པ་འདྲ་བོ་བྱེད་ཀིན་འདུག་ག་
* ་མཁས་པའི་གསུང་ནས་ང་ཚོ་+་མཁས་པས་གསུངས་ནས་ང་ཚོ་
* ་སྒྲུབ་བྱ་+་བསྒྲུབ་
* དབྱིན་ཇི་སྐད་ཀྱི་ནང་+་དབྱིན་ཇིའི་སྐད་ཡིག་ནང་
* ་དེ་འདྲའི་བསྒྱུར་+་དེ་འདྲ་
* ་གི་ཡོད་བ་རེད་དེའི་+་གིན་ཡོད་པ་རེད་དེ།
* བསྡུས་གྲའི་+་གྲྭའི་
* ་སྟངས་གིའི།+་ཀི
* ་རིག་ལམ་གིའི+་རིགས་ལམ་གི
* ་སྟངས་གི་+་ཀི་
* ་བྱས་ཉིའི་དེ།+་ཟེར་ངེ་དེ།
* ་དབྱིན་ཇི་ཚིག་+་ཇའི་
* ་ལོག་ལའི་ཡོང་གིའི་+་ལོག་ལའང་ཡོང་གིན་
* ་ཟེར་གིའི་འདུག+་གི་/གིན་
* ་ཐལ་ཕྱིར་བྱས་པ།+་ཐལ་ཕྱིར་ཟེར་ཡ་དེ།
* མ་རེད་པའི་+་མ་རེད་པས་
* ཁེགས་པོ+ཁག་པོ་
* རེ་བ་+རེད་པ།
* སྐད་གིའི་+་ཀི་
* དབྱེས་+ དབྱེ་
* བྱས་བྱས་ཅིག+་བྱེད་བྱས་བཅས་

2023-03-21 16:01 UTC, Jamtsul requested changes
སྐར་མ་23:26 ནས་བཅོས།
* ་བྱས་བྱས་ཅིག ཚང་མ་ལོ་གིའི་ཤེས་པ་+་བྱེད་བྱས། ཅིག་ཚང་མ་ལོ་གིས་ཤེས་པར་
* ཟེར་ཡ་ད།+ཟེར་ཡ་དང་།
* ་ཡ་གིའི་སྐད་+་གི་
* ་སྐོར་ཟེ་+་སྐོར་ཞིག་
* ་གཤེས་ག་+་གཤིས་ཀ་
* ་ཡ་རབ་སྐོར་ཟེ་+་ཡ་རབས་སྐོར་ཞིག་
* ་ནའི། གང་+་ན། གང་
* ལམ་སེང་+ལང་སང་
* ་དགོས་དེ་ཡིན་ན་དགོས།+་དགོས་ཀི་རེད། དེ་ཡིན་ན་དེ་ཡིན་དགོས་ཀི་རེད།
* ་དེ་ཁྱབ་གིའི་+་དེ་ཡིན་པའི་ཁྱབ་ཀི་
* ་ཁྱབ་གིའི་+་ཁྱབ་ཀི་
* ་་དག་ག་+ད་ག་
* ་སླེབ་ཅིག+་སླེབ་ཡ་ཞིག་
* ་ཁྱབ་གིའི་+་ཀི་
* ་དག་ཞིག་+་དག་ཅིག་
* ་ཇི་ཚིག་ནང་མ་ཟེ་ནིའི་+་ཇིའི་ཚིག་ལྟར་མ་སོང་ན་
* ་་་་་་་་+བརྒྱ་ཆ་བརྒྱ་ཞིབ་ཚགས་ཡོང་ཡ་ཞིག དེ་ཁྱད་པར་ཆེན་པོ་ཞེ་བོ་ཞིག་ཡོད་པ་རེད། མཁྱེན་སོང་ང་།
* ་སྤྱི་སྟེང་།+་སྤྱིར་བཏང་
* ་ངའི་ཨ་ད་རྡ་ལམ་ས་ལ་+་ང་ཨ་ད་རྡ་རམ་ས་ལར་
* ་ཕར་གིའི་+་ཕ་གིར་
* ་ཚུལ་གཉེན་+་ཚུར་
* ་ཡོངས་ཡ་+་ཡོང་ཡ་
* ་བཙུག་+་བཙུགས་
* ་ང་ཚོའི་ཡབ་མེས་ཞིག་གིའི།+ཡོང་ངེ་ཞིག་གིས།
* ་ཞིག་ལ་འཇལ་ཁ་རེ་ཅིག+་ཤིག་ལ་འཇལ་ཁ་ཞུས། 
* ་ལགས་ཞིག་+་ཤིག་
* ་ལགས་ཞིག་+་ཤིག་
* ་རྨོ་ལ་དེ་གིའི་+་རྨོ་ལགས་དེ་གིས་
* ་རྒྱ་མི་+་རྒྱ་མིས་
* ་རེ་བ།+་རེད་པ།
* ་ཅིས་ཙང་+་བྱས་ཙང་
*

2023-03-22 11:35 UTC, Jamtsul requested changes
སྐར་མ་24:43 ནས་བཅོས་ཡོད།
* ་ཟེར་ན་ལབ་པ་+་ཟེར་ལབ་པ་
* ་འདི་བསྡད་སྡོད་+་འདིར་
* ་ཡོད་བ་+་ཡོད་པ་
* ་ཚིགས་སྐྱོན་+་ཚིག་
* ་འགྱིག་+་འགྲིགས་
* ་ཡོད་བ་རེད་བ་+་ཡོད་པ་རེད་པ་
* ་སྤྱི་སྟངས་+་སྤྱིར་བཏང་
* ་ཅེས་ཉིའི།+་བྱེད་ངེ་།
* ་ཉའི་ཟེར་+་ངེ་ཟོར་
* ་བཤད་ཅེས་+་ཀྱིས་
* ་ཤེས་ཉིའི་+་ཤེས་ངེ་
* ་ཁྱབ་གིའི་+་ཀི་
* ་བསྡད་གིའི་+་བསྡད་ཀི་
* ་ཕན་ཐོག་ཡོད་བ་+་ཕན་ཐོགས་ཡོད་པ་
* ་དེ་གིའི་+་དེ་གའི་
* ་རུ་པོ་ཁོ།+་འདྲ་བོ་ཁོ།
* ་དེ་ཐོག་ནས་དོའི་སུ་རྩལ་+་དེའི་ཐོག་ནས་འདུག་སེ་རྩད་
* ་བྱས་བ་+་བྱས་པ་
* ་ཡའི་ཞེས་གྲགས་ཕན་གིའི་+་ཡང་ཞེ་དྲག་ཕན་གི་
* སོ་སོའི་ཅིག་+སོ་སོས་
* ་མིན་གིའི་ཐག་ཟེ་+་མིན་གི་ཐག་ཅིག་
* ་ཤུལ་གོ་དེ་དག་དག་འགྲོ་བསྡད་ཉིའི་ཅིག+་གཞུག་གུར་དེ་ཏག་ཏག་འགྲོ་བསྡད་ངེ་ཞིག
* ་ཞིག་ཉམས་དུ་རྩལ་ཞིག་རྒྱག་+་ཅིག་མཉམ་དུ་རྩེད་ཅིག་བརྒྱག་
* ་སོ་སོའི་ཐག་+་སོས་
* ་སོ་སོའི་བསམ་+་སོས་
* ་བཏང་དེ་ཡིན་ན་+་བཏང་ནས་དེ་ཡིན་ན་
* ་དགོས་དེ་ཡིན་ན་དེ་ཡིནདགོས་+་དགོས་ཀི་རེད། དེ་ཡིན་ན་དེ་ཡིན་དགོས་ཀི་རེད།
* ་ཁྱབ་གིའི་རེད་དེ་ཡིན་ན་དེ་མ་ཡིན་པའི་ཁྱབ་དགོས་རེད་+་ཁྱབ་ཀི་རེད། དེ་ཡིན་ན་དེ་མ་ཡིན་པའི་ཁྱབ་ཀི་རེད་
* ་རོ་ཅིག+་འདྲ་བོ་ཞིག
* ་ཤར་ཅེས།+་ཤར་གྱིས།
* ་ཤིག་གི་ཚུལ་རྩལ་ཞིག་རྒྱབ་པ་ཡིན་ནའི།+་ཞིག་གིས་ཚུར་རྩེད་ཅིག་བརྒྱབ་པ་ཡིན་ནའང།
* ་རུ་ཁོ་རྩལ་མཁྲེགས་པོ་ཞིག་ཟུམ་ཐུབ་གིའི་+་འདྲ་བོ་ཁོ་བརྩད་མཁྲེགས་པོ་ཞིག་ཟིན་ཐུབ་ཀི་
* བཞན་གང་མཚམས་ཞིག་ནས།+གཞན་གང་མཚམས་སོ་ནས།
* ་གང་ཟེར་ནས་མགོ་ཕུར་ཕུར་བསྡད་ཀྱོས་ཁས་གིའི་རེ་བ། མཁྲེན་+་གང་ཤེས་ཟེར་ནས་མགོ་འཕུར་འཕུར་བསྔད་རྒྱུ་ཁེལ་གི་རེད་པ། མཁྱེན་
* ་གྲྭ་ནང་+་གྲྭའི་ནང་
* ་བུ་གུ་ཚོའི་+་ཚོས་
* ་སློབ་ཡ། དོ་སྣང་+་སློབ་ཡ་ལ་དོ་སྣང་
* ་མེད་དྲོའི་+་མེད་འགྲོ་
* ་ང་ཚོའི་སྔོན་མ་བསླབ་+་ང་ཚོས་སྔོན་མ་བསླབས་
* ་གསར་པོ་དྲན་གིའི།+གསལ་པོ་དྲན་གི
* ་སུམ་ལ་+་སིམ་ལའི་
* ་ལ་ཡིའི་ང་ཕྱིན་པ་རེད།+་ལ་ང་ཕྱིན་པའི་ཁ་ཐུག་ལ།
* ་མ་སོར་རེ་+་མ་སུ་རིའི་
* ་ང་ཚོའི་རྟགས་+་ཚོས་
* ་བཏང་བ་དེ་འདྲའི་བྱས་བ་+་བཏང་དེ་འདྲ་བྱས་པ་
* ་ནི་ལེ་ཁོ། ད་ཞོལ་གོའི་སྐྱོང་+་ནའང་ཁོ། གཞུག་གུ་བསྐྱལ་
* རྗེས་མ་འཁྱོལ་+གཞུག་གུ་མ་འཁྱོལ་
* རེ་བ།+རེད་པ།
* ་དེ་གིའི་དེ་+་དེ་གས་དེར་
* ་གནང་བཞིན་+་ནང་བཞིན་
* ་དུས་དུས་+་དུས་ཚོད་དུས་ཚོད་
* ་ཁ་ཤས་ལ་དེ་འདྲའི།+་ཁ་ཤས་འདྲ་བོ་དེ་འདྲ།
* ་རོ་དེ་འདྲའི།+་འདྲ་བོ་དེ་འདྲ།
* ་འདྲའི་གིའི་+་འདྲའི་
* ་ཉིའི་ཚོའི་ཡང་དམིགས་གསལ་གིའི།+་མཁན་ཚོས་ཡང་དམིགས་བསལ་གིས།
* ་གཅིག་ཟེ་འདྲ་བོ།+་གཅིག་ཟི་འདྲ་བོ།
* ་གཉིས་རིང་ལ་+་གཉིས་ཟི་རིང་དེ་འདྲར་
* ་་ཡ་ཅིག +་ཞིག
* ་འདྲའི་བྱས་+་འདྲ་བྱེད་
* ་མིན་དྲོའི་དྲན་+་མིན་འགྲོ་བསམ་དྲན་
* ་ཚོའི་སེམས་ལ་ཞིག་ཞག+་ཚོས་སེམས་ལ་ཅིག་གཞག
* ཨ་ནེ་འབྲེལ་ཡོད་ཚོའི་སེམས་ལ་ཞིག་ཞག+ཨེ་ནས་འབྲེལ་ཡོད་ཚོས་སེམས་ལ་ཅིག་གཞག
* ད་ཅེས་ན།+ད་བྱས་ན།
* ་དེ་འཕྲོ་+་དེའི་འཕྲོ་
* ་སྒྲུབ་གིའི་འདི་འདྲའི་ཞིག་གསུང་བ་+་སྒྲུབ་ཀིས་འདི་འདྲ་ཞིག་གསུངས་པ་
* ་སྒྲུབ་གིའི།+་ཀི
* ་ཟེར་གིའི་+་གི་
* ་ཟེར་གིའི་+་གི་
* ་ད་ཡིན་ན་+་ག་རེ་ཡིན་ན་
* ་ད་ཡག་པོ་ཞིག་དཔེ་ཆ་ག་འདྲ་སུ་དྲན་ན་སོང་།+་ངས་ཡང་དཔེ་ཆ་ག་ནས་ཡིན་དྲན་མ་སོང་།
* ་སྒྲུབ་གིའི་གསུང་རེད+་སྒྲུབ་ཀིས་གསུངས་རེད།
* ་སྒྲུབ་གིའི་གསུང་ནང་+་སྒྲུབ་ཀི་གསུང་གི་ནང་
* ་སྡོད་པ་དེ་ནང་གིའི+་བསྡད་པ་དེའི་ནང་གི
* ་རེད་ཅེས་གསུང་བ་+་རེད་ཟེར་བྱས་ནས་གསུངས་པ་
* ་རེད་ཅེས་ལབ་+་རེད་ཟེར་ལབ་
* ་འདས་ཀྱི་རྟེན་+་ཀྱིས་
* ་དེ་གིའི་+་དེས་ཀིས་
* ་དེས་གིའི།+་ཀིས་
* ་་དེས་གིའི།+་ཀིས་
* ་གིས་རེད།+་གི་
* ་་དེ་གིའི།+་དེས་ཀིས་
* ་མཐོང་གིས་རེད་ཅེས་ཟེ་ནས+་མཐོང་གི་རེད་བྱས་ནས་
* ་ཚུལ་ཕྱོགས་དེ།+་ཚུར་ཕྱོགས་དེར།
* ་སྒྲུབ་གིའི་+་ཀི་
* དག་ག་གནང་བཞིན་+དེ་ག་/ད་ག་ནང་བཞིན་
* ་ནང་ལ་ཡའི་+་ཡང་
* ་རེད་ཟེ།+་ཟེར།
* ་སྒྲུབ་ཡ་ལ་+་བསྒྲུབ་
* ་དེས་སྒྲུབ་+་དེ་བསྒྲུབ་
* མདོར་ན། ཆོས་ནི་མི་འཚེ་དང་མྱ་ངན་འདས་པ་རྣམ་པ་གཉིས།+མདོར་ན་ཆོས་ནི་མི་འཚེ་དང་།། མྱ་ངན་འདས་པ་རྣམ་པ་གཉིས།།
* ་གཅིག་ད+་དང་
* ་གཉིས་གསུམ་ཡོད་བ་+་གཉིས་གསུང་གི་ཡོད་པ་
* ་ཡིན་པས། དེ་གནད་+་ཡིན་པའི། དེའི་གནད་
* ་་ཟེ་ནས་+་ཟེར་
* ་ནང་ལོག་ལ་གསུངས་བ་གནང་བཞིན་ཅེས་+་ནང་ལ་གསུངས་པ་ནང་བཞིན་བྱས་
* ་སྒྲུབ་བྱ་+་བསྒྲུབ་བྱ་
* ་ཡོད་བ་རེད་ཟེ།+་ཡོད་པ་རེད་ཟེར།
* ཟེ་འ་དེ་འདྲའི་+་དེ་འདྲ་
* ་ཡ་གིའི་+་གི་
* ་རེད་ཟེ།+་ཟེར།(འདི་འདྲ་འདིའི་གོང་འགབ་ལ་ལྔ་ལྷག་འདུག)
* སྡོམས་པའི་+་སྡོམ་པའི་
* ་སྒོམས་+་བསྒོམ་
* ་ཉམས་ལེན་སྒྲུབ་+་མྱང་འདས་བསྒྲུབ་
* ་་འབྱུང་དེས་+་་འབྱུང་བ་མཐོང་བ་དེས་
* ཅེས་གསུང་དེ་གིའི།+ཟེར་ནས་གསུང་བསྡད་ཡ་དེ་གི
* ་བཤད་པ་རེད།+་བཤད་བྱས།
* ་སྒྲུབ་གིའི་གཞུང་ནང་ལོག་ལ་+་སྒྲུབ་ཀི་གཞུང་ནང་ལ་
* ་ཞེས་གྲགས་ཡོད་རེ་བ། ཅེས་ནས། ཕར་གིའི།+་ཞེ་དྲག་ཡོད་རེད། བྱས་ན་ཕ་གིར།
* ་གསར་དུ་གསར་པ་གཏོད་+གསལ་དུ། གསལ་ཁ་བཏོད་
* ་འབྲེལ་ད།+་དང་།
* ་ཅེས་གཉིས་འདུག་+་ཟེར་ནས་གཉིས་གསུངས་འདུག་
* ་འབྲེལ་ཟེ་+་ཟེར་
* ་་ལོའི་གསུངས་གིའི་ཡོད་བ་+་་ལོས་གསུང་གིན་ཡོད་པ་
* ་བའི་གསུངས་གིའི་ཡོད་བ་+་བས་གསུང་གིན་ཡོད་པ་
* ་འབྲས་གིའི་+་ཀི་
* ་ཁྱབ་གིའི་ཡོད་བ་+་ཁྱབ་ཀི་ཡོད་པ་
* ་འབྲས་གིའི་+་ཀི་
* ་རྒྱུ་ཙམ་+་རྒྱུ་དང་རྐྱེན་ཙམ་
* ་་ལ་བརྟེན་ནས་འབྱུང་བ་+་ལས་བྱུང་བ་ཡང་
* ་མེད་གིའི། འདིའི །   ཕར་ཆེར་+་མེད་ཀི འདི། ཕལ་ཆེར་
* ་འབྲེལ་གིའི་+་གི་

2023-03-23 11:51 UTC, Jamtsul requested changes
stt003-005འགོ་ནས།

1. ་འབྲེལ་ཀི་+་གི་
2. ་ཅེས་ནས།+་ཅེས་ཟེར་ནས་
3. ་ཡོད་ལ་+་ཡོད་པ་ལ་
4. ་སྐྱེས་བ་+་པ་(འདི་དང་གཅིག་པ་5འདུག)
5. ་ཅེས་སུ་+་ཅེས་ཟེར་ནས་
6. ་དེ་ཀི་+/གི་
7. ་མེད་ཀི་+་ཀིས་
8. ་རེད་ཟེ་+་ཟེར་
9. ་དེ་ཀི་རྐྱེན་གསུམ་གསུངས་ཀི་ཡོད་བ་རེད་ཟེ།+་དེ་གིས་རྐྱེན་གསུམ་གསུང་གིན་ཡོད་པ་རེད་ཟེར།
10. ་ཟེར་ན།+་ཟེར་ལབ་ན་
11. ་རྐྱེན་ཟེ།+་ཟེར།
12. ་དེ་གས་མདོ་དེ་ག་འདྲ་ཟེ་གླེང་གི་ཡོད་བ་རེད་ལབ་+་དེ་ག་མདོ་དེ་གས་ག་འདྲ་སེ་བསྟན་གི་ཡོད་པ་རེད་ལབ་
13. ་དེ་ཀི་+་དེ་གིས་
14. ་རེད་ཟེ། དེ་དོན་+་རེད་ཟེར། དེའི་དོན་
15. ་ཅེས་ནས་+་བྱས་ནས་
16. ་རེད་ཟེ།+་རེད་ཟེར། (ཟེ་རྗེས་སུ་ཤད་ཅན་འདི་དང་གཅིག་མཚུངས་13འདུག)
17. ་རྐྱེན་ཀི་+་གིས་
18. ་འདི་འདྲས་+་འདི་འདྲ་
19. ་འབྱུང་མཁྱེན་+་འབྱུང་ཟེར། མཁྱེན་
20. ་ཙམ་ཀི་+་གིས་(འདི་དང་གཅིག་པ་4འདུག)
21. ་ཉེན་+་ངེ་(འདི་དང་གཅིག་པ་3འདུག)
22. ་འདྲས་+་འདྲ་(འདི་དང་གཅིག་པ་15འདུག)
23. ་ཡོད་བ་+་པ་(འདི་དང་གཅིག་པ་24འདུག)
24. ་དེ་བྱས་ད་དེ་ནས།+དེ་བྱས། ད་དེ་ནས།
25. ་སྐྱེས་བ་ལ་འདི་+་་སྐྱེས་པ་དང་། འདི་
26. ་སྐྱེས་བར་+་སྐྱེ་བར་
27. ་ཉེན་ཀི་+་ངེ་གི་(འདི་དང་གཅིག་པ་5འདུག)
28. ་རྐྱེན་གྱི་+་གྱིས་
29. ་དགོས་བ་+་པ་(འདི་དང་གཅིག་པ་2འདུག)
30. ་རེད་ཟེ་+་ཟེར་(ཟེ་གི་རྗེས་སུ་ཚེགས་ཡོད་པ་8འདུག)
31. ་བཀག་ཀི་+་གི་
32. ་ག་རེད་ཟེ་+་ག་རེ་ཟེར་
33. ་གཅིག་གི་སྐྱེས་བའི་ཆོས་ཞིག་+་གཅིག་གིས་སྐྱེས་པའི་ཆོས་ཤིག་
34. ་གི་སྐྱེད་+་་གིས་བསྐྱེད་/སྐྱེས་
35. ་རྒྱུའི་སྐྱེད་+་རྒྱུས་བསྐྱེད་
36. ་བཞིན་ཀི་+་གི་
37. ་བཞིན་ཀི་ཆོས་སྐྱེད་+་བཞིན་གི་ཆོས་བསྐྱེད་
38. ་འདུག་ག་ཟེ་འ་དེ་+་འདུག་ག ཟེ་འ་དེ་
39. ་འདས་ཀི་+་ཀིས་
40. ་འབྱུང་ཞེས་ནས་+་ཟེར་བྱས་ནས་
41. ་ཡོད་བ་གསུང་བ་+་་ཡོད་པ་གསུངས་པ་
42. ་སྐྱེས་བས་+་པས་(འདི་དང་གཅིག་པ་2འདུག)
43. ་འདི་སྐྱེས་ཞེས་ཟེ་ཡོད་+་འདི་སྐྱེས་ཟེར་བྱས་ནས། ཡོད་
44. ་ཡ་ཀི་+་གི་
45. ་འབྲས་བུ་སྐྱེད་+་བསྐྱེད་
46. ་ཚུན་ཆད་+་ཕྱིན་ཆད་
47. ་ལས་སྐྱེ་བ་+་ལས་སྐྱེས་པ་
48. ་བཞིན་གཅིག་+་བཞིན་ཞིག་
49. ་སྐྱེས་ཞེས་ནས་+་སྐྱེས་ཟེར་ནས་
50. ་འདས་ཀི་+་ཀིས་(འདི་འདྲ་6འདུག)
51. ་མེད་ཀི་+་ཀིས་
52. ་རྐྱེན་ཟེ་གསུང་བ་རེད་ད་མི་རྟག་+་རྐྱེན་ཟེར་གསུངས་པ་རེད་ད། མི་རྟག་
53. ་མི་རྟག་པའི་མི་རྟག་པ་+་མི་རྟག་པའི། མི་རྟག་པ་
54. ད་དེ་ཕྱི་ཀོ་དེ།+ད་དེའི་གཞུག་གུ་དེ། 
55. ་འདུས་ཀི་+་འདུས་བྱས་ཀི་
56. ་ཅིག་ཀི་+་ཞིག་གིས་
57. ་ཚོགས་ཞིག་སྐྱེད་+་ཚོགས་ཤིག་བསྐྱེད་
58. ནུས་བའི་+་པའི་(འདི་འདྲ་2འདུག)
59. ་བྱེད་ཞེས་གསུངས་+་བྱེད་ཟེར་ནས་གསུངས་
60. ་འགྲུབ་ཀི་རྒྱུ་+་འགྲུབ་བྱེད་ཀི་རྒྱུ་
61. ་སྐབས་འདི་འདུ་བྱེད་ཟེར་ཡ་གས། རྒྱུ་དེ་འབྱུང་+་སྐབས་འདིར་འདུ་བྱེད་ཟེར་ཡ་གི་རྒྱུ་དེ། འབྱུང་
62.

2023-03-24 05:06 UTC, Jamtsul requested changes
(stt003-005) སྐར་མ་35:39ནས་བཅོས་ཡོད།

1. བསྔལ་ཀི་+་བསྔལ་གི་(འདི་འདྲ་7འདུག)
2. ་བསྒྲུབ་ན་+་སྒྲུབ་ངེ་
3. ་ཡོད་བ་རེ་བ་+་ཡོད་པ་རེད་པ།
4. ་ཡོད་བ་ཟེ།+་ཡོད་པ་ཟེར།
5. ་ཡོད་བ་རེད་ཅེས་ནས་+་ཡོད་པ་རེད་ཟེར་བྱས་ནས་
6. ་དུས་སུ་+་འདུག་སེ་
7. ་ཐུབ་ཉེན་ཞིག་ཀི་+་ཐུབ་ངེ་ཞིག་གི་
8. ་བསྡད་ཉེན། དེ་འདྲས་+་བསྡད་ངེ་། དེ་འདྲ་
9. ་བུས་ཀི་+་བྱས་
10. ་དེ་ཐོག་+་དེའི་ཐོག་
11. ་ཚར་རེ་བ་+་ཚར་བ་རེད་པ་
12. ་ག་འདྲས་སུ་+་ག་འདྲ་སེ་
13. ཉོན་གཉིས་ཀི།+་ཀིས་
14. ་རེད་ཅེས་+་རེད་ཟེར་བྱས་
15. ་འདྲི་བ་+་དྲི་བ་
16. ་གསར་བཤད་+་གསལ་
17. ་སྐྱེས་མཆེད།+་སྐྱེ་
18. ཕྱི་གོ་+་གཞུག་གུ་
19. ་དེ་གས་གནད་+་གའི་
20. ་དེ་ཀི་+་གིས་
21. ་རེད་ཞེས་ནས་+་རེད་ཟེར་བྱས་ནས་
22. ་དེ་ཀི་བྱས་བ་རེད་ཞེས་ནས་+་དེ་གིས་བྱས་པ་རེད་ཟེར་བྱས་ནས་
23. ་གསུངས་ཡོངས་+་ཡོང་
24. ་དགོས་རེད་ཟེ་+་དགོས་ཀི་རེད་ཟེར།
25. མ་རིག་ལྡོག་+་མ་རིག་པ་ལྡོག་
26. ་ལྡོག་ཀི་+་གི་
27. ་པ་དེ་དབང་+་དེའི་
28. ་བསྔལ་ཀི་རྒྱུ་བསགས་ཡ་+་བསྔལ་གི་རྒྱུ་བསགས་བཞག་ཡ་
29. ་འགྲོ་ཀི་རེ་བ་+་གི་རེད་པ།
30. ་གཉིས་བོ་+་པོ་
31. འདུ་བྱེད་ཀི་+་ཀིས་
32. ་སྒོ་གནས་+་སྒོ་པའི་གནས་
33. ་བསྒོ་ནས་+་བསྒོས་
34. ང་ཚོའི་མི་འདོད་པ་+་ཚོས་
35. ་དེ་གས་དེའི་+་དེ་གས་དེ་
36. ་དེ་རྒྱུ་དང་པོ་+་དེའི་
37. ་ཡ་ཀི་+་གི་
38. ་བསྐྱེད་བྱེད་+་སྐྱེད་
39. ་ཡ་དེ་སྡུག་+་ཡ་དེ་ཡང་སྡུག་
40. ་བསྐྱེད་བྱེད་+་སྐྱེད་
41. ་སྐྱེས་བས་+་པས་
42. ཐར་པའི་+་བའི་
43. ་སྒྲུབ་བྱ་+་བསྒྲུབ་
44. ་ཏིང་ངེས་ཀི་+་ཏིང་ངེ་འཛིན་གི་
45. ་དགོས་རེད་ཞེས་ནས་+་དགོས་ཀི་རེད་ཟེར་བྱས་ནས་
46. གསུངས་བ་+་པ་
47. (སྒྲ་ཐག་5 ཡོངས་སུ་ཚར།)

2023-03-25 19:18 UTC, Jamtsul approved these changes
2018-ནང་ཆོས་ངོ་སྤྲོད་ཉིན་གཉིས་པ། སྒྲ་ཐག་05ཆང་ཚང་ལ་སྐར་མ་31:30ཅན་ཞིག་དང་དེའི་འཕྲོ་མ་སྐར་མ་31:31ནས་40:46ཅན་བཅས་དུམ་བུ་གཉིས་པོ་ལ་བསྐྱར་བཅོས་ཚར་གསུམ་རེ་སོང། ལས་བྱེད་པ་བློ་བཟང་ལྷུན་འགྲུབ།

2023-03-27 05:57 UTC, Jamtsul requested changes
སྒྲ་ཐག་06 པའི་འགོ་ནས་བཅོས།

1. ་ངེ་ཀི +ངེ་གི།
2. ཡོང་ཡ་མཐའ་+་ཡོང་ཡ་གི་མཐའ་
3. ་ཡ་ཀི+་གི།(24)
4. ་དེ་ཀི་གྲོགས་+་དེ་གས་གྲོགས་
5. ་འདས་ཀི་+་ཀིས་
6. ན་ནིང་+་འདའ་ཉིན་
8. ད་ཀི་+་ད་དེ་གའི་
9. ་ཟེར་ཀི་+་གི་(12)
10. ་བསྡད་པ་རེད།+་བསྡད་པ་ཞིག་རེད།
11. ་བཀོད་པ་པོའི་+་པོས་
12. ་ཟོལ་+་ཟོར་(9)
13. ་རྐྱེན་ཀི་+་གིས་(བྱེད་པའི་དོན་ཅན་4དང་དྲུག་སྒྲའི་དོན་2བཅས་6)
14. ་དུས་སུ་+འདུག་སེ་(8ལས་གཅིག་མ་གཏོགས་པ་འདུག་སེ།)
15. ་འགྲོ་ཀི་+་གི་(6)
16. རེད་ཟེ་+་ཟེར་(18)
17. ་གསུངས་བ་+་པ་(2)
18. ་ཉིན་རེ་འཚོ་+་རེའི་
19. ་བྱིའུ་ཚོའི་+་ཚོས་
20. ་འདྲ་ཞིག་+་འདྲ་བོ་ཞིག་
21. ་བཟོ་ཀི་+་གི་(2)
22. རེད་ཁོ།+་ཁོས།
23. ་ཡོངས་ཡེ་+་ཡོང་ཡ་(2)
24. ་ཟེར་ཡ་མི་+་ཟེར་ཡ་ཞིག་མི་
25. ་དེ་གང་ཞེས།+་ཤེས་
26. ་དུས་སུ་བཟོ་+་འདུག་སེ་བཟོས།
27. སྒོ་ང་འདི་ཡོད་+་འདིར་
28. དཔེ་དུ་+་རྦད་དེ་
29. ་ཀྱོག་ཞིག་+་ཅིག་
30. མི་དཔེ་ལག་པ་རྩེབས།+མིའི་དཔེ་ལག་པས་སྩེབས།
31. ་ཁེགས་པོ།+་ཁག་པོ་
32. ་གཟིངས་ཅིག་+་གསེང་ཞིག་
33. 03.06བར

2023-03-28 18:07 UTC, Jamtsul requested changes
stt003-06-སྐར་མ་ 03:06 ནས་བཅོས་ཡོད།

1. ཁོ་ཤེས་ཀི་འདུག་ག་ཁོའི།+ཁོས་ཤེས་ཀི་འདུག་ག ཁོས།
2. ་འདུག་ག་ཁོའི་རྒྱུ་+་འདུག་ག ཁོས་རྒྱུ་
3. ་ཏོག་སུ་+་ཏོ་ཟི་(4)
4. ་ཁོ་ཚོའི་+་ཚོས་
5. ་རེ་བ།+་རེད་པ།
6. ་ད་སྤྲུལ་དེ་+་སྦྲུལ་
7. ་གྲས་ཀི་ཤེས་+་ཀིས་
8. ་དུས་ཙ།་+་དུས་ཙ་ནས།
9. ་མི་ཚེ་སྨད་+་མིའི་
10. ་བྱས་བ་+་པ་
11. ་ཆགས་བཞག་+་ཆག་བཞག་(8)
12. ་མཁྱེན་སུ་+་ཟེར་
13. ་རེད་བྱས་དྲན་+་རེད་བསམ་ནས་དྲན་
14. ་མེད་བ་ང་ཚོ་+མེད་པ་ང་ཚོས་
15. ་བྱས་ཙང་ད་དེ།+་ད་དེ།
16. ་རྒྱས་བ་+་པ་
17. ་བྱས་རྒྱུས་+་བྱེད་རྒྱུ་
18. ་རྒྱུ་མ་སྒྲུབ་ན།+་གྲུབ་
19. ་དཔེ་དུ་+་རྦད་དེ་
20. ་འོས་བ།+་པ།
21. ད་དཔེ་དུ་ཞེ་བོའི་+་ད་དཔེ་ཞེ་བོ་
22. ་དཔེ་དུ་སྡུག་+་དཔེ་སྡུག་
23. ་ཟ་ཀི་+་གི་
24. རེ་བ།+རེད་པ།(13)
25. ་ལང་བྱས་+་ལངས་
26. ་ང་རང་བསགས་+་ང་རས་བསགས་
27. ་འདེད།+་འདེད་ནས།
28. ཁོའི་འགྲིག་+ཁོས་
29. ་འདྲ་བྱུང་+་འདྲ་བོ་བྱུང་
30. ་ང་རང་ལས་+་ང་རའི་ལས་
31. ་ཕན་ཀི་+་གི་
32. ་ཁོའི་བཟོ་+་ཁོས་
33. རྙོག་གྲ་+་དྲ་(2)
34. སྣོན་པའི་+་པ་
35. ་བྱས་བ་རེད་+་བྱས་པ་རེད་ཟེར་
36. ་བསྡད་ཡ་ཞིག་ད།+་བསྡད་པ་ཞིག་དང་།
37. ་འཕྲད་ཀི་+་འཕྲལ་གི་
38. རྐྱེན་ཀི་+་གི་
39. ་རྐྱེན་དང་མཚམས་པ་ཚར་+་རྐྱེན་དུ་འཚམས་པར་ཚར་
40. ་ཟེར་ནས་ཡོད་པ་+་ཟེར་བྱས་ནས་
41. ་དང་མཚམས་པའི་+་འཚམས་
42. རྐྱེན་ཀི་རྒྱུ་འབྲས་+་གི་(6)
43. ་་ཡ་ཀི་+་གི་(19)(མཐའ་མེད་ཡོངས་རྫོགས་ཀི་རྗེས་སུ་ཨི་ལྡན་འདི་ལྟར་འབྲི་རོགས།)
44. ་དེ་ཀི་+་དེ་གའི་
45. ་ཞིག་ཀི་+་གི་(6)
46. ་རླུང་གིས་འགྲོ་སྟངས་+་གི་
47. ་དགོས་བ་+་པ་
48. ་བྱེས་བྲག་+་བྱེ་(2)
49. ་མི་ཡིན་རེད་+་མི་ཡིན་ན་རེད་
50. ་གང་ཡིན།+་གང་ཡིན་ན་རེད།
51. ་སེམས་པའི་དཔེ་+་པས་
52. ་དེ་ཁ་ཐུག་+་དེའི་ཁ་ཐུག་
53. ་ཉིན་ཀི་+་གི་
54. ་ཡོད་པ་ཞིག་+་ཡོད་པ་བསམ་ཞིག་
55. ་ཟ་ཟས་+་ཟ་སའི་(2)
56. ་འགྲོ་ཀི་+་གི་
57. ་པོ་ཐོག་+་པོ་ཞིག་གི་ཐོག་
58. ་མ་ལོག་+་ལོར་
59. ་ལུས་ཡོད་པ་དེ་+་དེར་
60. ་ཡོང་པའི་རྐྱེན་ཀི་+་ཡོད་པའི་རྐྱེན་གིས་
61. ་དུས་སུ་+་འདུག་སེ་
62. ་བཞིན་ཀི་རྒྱ་+་གིས་
63. ་ཡུག་གནས་+་ཡུག་གི་གནས་
64. ་ཤེས་གསར་+་གསལ་
65. ་གཅིག་བུའི་+་པུའི་
66. ་ལས་ཏེ་+་ལས་པ་དེ་
67. ་ཕན་ཀི་+་གི་
68. ་འབྲས་རྟེན་+་འབྲས་ཀི་རྟེན་
69. ་ངའི་ཡིད་ཟབ་+་ངས་ཡིད་གཟབ་
70. ་ཅིག་ཀི་+་གི་
71. ་ནང་ལོག་+་ལོགས་
72. ་བོད་དོན་+་བོད་རྒྱའི་
73. ་དབུ་མ་བའི་+་བས་
74. ་སེམས་ཙམ་པའི་+་པས་
75. ་ཙམ་པའི་+་པས་
76. ་རེད་ཟེ་+་ཟེར་
77. ཟེ་ནས་+ཟེར་
78. ་དེ་ཀི+་དེ་གས།
79. ་ནང་བཞིན་ཀི་+་གི་
80. ་ལས་བརྟེན་+་ལས་ལ་བརྟེན་
81. ཞེས་ནས་གསུངས་+ཟེར་ནས་གསུངས་
82. ་འོ་ད་དེ་ཀི་+་འོ་ད་དེ་གས་
83. ་ཡ་དེ་ཀི་+་ཡ་དེ་གས་
84. ་ངེ་ཞིག་འཚེམ་+་ངེ་ཞིག་གིས་འཚེམ་
85. རེད་བ་ཡ།+་པ་
86. འཚེམ་བོའི་+་པོའི་(2)
87. ་འཚེམ་པོ་བ་བྱེད་པ་པོར་+་བའི་
88. ་འབྲས་སྐད་ཆ་+་འབྲས་ཀི་སྐད་ཆ་
89. ་གནང་བཞིན་+་ནང་(3)
90. ་རྐྱེན་ཟེ་གསུངས་བ་གནང་བཞིན་ཀི་+་རྐྱེན་ཟེར་ནས་གསུངས་པ་ནང་བཞིན་གི་
91. ་སྐྱེད་བྱེད་ཀི་རྒྱུའི་སྐྱེད་+་སྐྱེད་བྱེད་ཀི་རྒྱུས་བསྐྱེད་
92. (11:57)

2023-03-29 05:32 UTC, Jamtsul requested changes
stt003-06-སྐར་མ་ 11:57 ནས་བཅོས་ཡོད།

1. རྒྱ་དེ་+་རྒྱུ་
2. ་པས་ལབ་+པས་ཟེར་ལབ་
3. ་ཟེར་ན་མ་རེད་+་ཟེར་ལབ་ན། མ་རེད་
4. ་ཟེར་ན།+ཟེར་ལབ་ན།
5. ་རྒྱུ་ཞེས་ལབ་+་རྒྱུ་ཟེར་ལབ་
6. ་ནང་བཞིན་ད་+་ནང་བཞིན་ཞིག་ད་
7. དེ་ལ་བསམ་ནས་དེ་ལ་ལྟོས་པས་རྒྱུ་+་དེ་ལ་ལྟོས་ཏེ་རྒྱུར་
8. ་གཏིང་རིང་བོ་གང་ཅིའི་འདུག་ག་འུ་ད་འོ་དེ།+་གཏིང་རིང་བོའི་སྒང་ལ་སླེབ་ཀི་འདུག་ག འུ། ད་འོ་དེ།
9. ་གཞན་ཞེས་བསམ་+་གཞན་ཟེར་ནས་བསམ་
10. ་གཞི་དེ་ད།+་གཞི་དེ་དང་།
11. ་ཀ་ཡོད་ལོག་ཡོད་དགོས་+་ཀ་ལོ་ཡོད་དགོས་
12. ་རེ་བ།+་རེད་པ།(13)
13. ་སྐྱེས་བའི་+་པའི་
14. ད་དེ་དོན་རྩ་བ་+་དེའི་
15. ་ལས་མིན་མ་རེད་མ་རེད་དེ།+་ལས་མིན།། མ་རེད་དེའི་གཞུག་གུ་དེ།
16. ་མ་ཡིན་མ་རེད་མ་རེད་ག་རེ་ཟེ་ཅིག་ཟེ་དེ་ལས་+་མ་ཡིན་རྒྱུ་མེད་མིན།། འུང་འུང་། ག་རེ་ཟེར། ཅིག་ཟེར།
17. ག་རེ་ཟེ་བདག་གི་དངོས་པོ་ཨ།+ག་རེ་ཟེར། བདག་གི་དངོས་པོ། ཨ།
18. ་ག་ལ་ཡིན།།གསུངས་བསྡད་ཡ་དེ་+་ག་ལ་ཡིན།། ཟེར་འོ་གསུངས་བསྡད་པ་དེ་
19. ་འགྱུར་བསམ་+་འགྱུར་ལ་བསམ་
20. ་གྲུབ་རྒྱུའི་རེད་པ་+་རྒྱུ་
21. ་གྲུབ་རྒྱུའི་རེ་བ།+་གྲུབ་རྒྱུ་རེད་པ།
22. ་གྲུབ་རྒྱུའི་རེ་བ།+་རྒྱུ་རེད་པ།
23. ་ཟབ་རེ་+་རུ་
24. ་ཟེ་གཅིག་+་ཟེར་ཡ་གཅིག་
25. ་ཅན་ཀི་+་གི་
26. ་ཤས་ལྟོས་+་ཤས་ལ་ལྟོས་
27. ་ལྟོས་གྲུབ་ཅེས་ནས་+་ལྟོས་གྲུབ་ཟེར་བྱས་ནས་
28. ་ཅར་ལོག་+་ཆ་ལོ་
29. ་ཟླ་བ་གྲགས་པའི་+་པས་
30. ་སྒྲུབ་དགོངས་+་སྒྲུབ་ཀི་དགོངས་
31. ་སྟོང་པར་ཡང་དག་པར་རྗེས་སུ་ལྟའོ་ཞེས་གསུངས་+་སྟོང་པར་རྣམ་པར་ཡང་དག་པར་རྗེས་སུ་བལྟའོ།། ཟེར་བྱས་གསུངས་
32. ་འདྲ་པོ།+་བོ།
33. ་མཁྱེན་བར་+་མཁྱེན་གི་བར་
34. ་པ་དངའི་བཀྲལ་+་པ་ལྟར་བཀྲལ་
35. ་འདྲ་སུ་+་སེ་
36. ་རེད་ཟེ་ལབ་+་ཟེར་
37. ་རྟོག་པའི་བཏགས་ཙམ་རེད།+་རྟོག་པས་བཀོད་ཙམ་རེད།
38. ་སྙད་ཚད་མ་+་སྙད་པའི་ཚད་མ་
39. ་རྒྱུས་ཡི་+་རྒྱུ་
40. ་ལྟོས་བྱ་འབྲས་བུ་+་བྱའི་
41. ་དེ་ཀི་བྱ་བ་+་གིས་(14)
42. སྐྱེད་བྱའི་+་བསྐྱེད་
43. ་འདུག་ག་གོ་གས་+་འདུག་ག གོ་གི་
44. ་མཐར་ཐུགས་+་ཐུགས་
45. ་ཀི་བརྩལ་དུ་+་ཀིས་
46. ་ཕབ་ཡ་དེ་དེའི་རེད།+་ཕབ་ཡ་དེ་དེ་རེད།
47. ་ཐོགས་མེད་རང་གི་ད།+་གིས་
48. ་གཅིན་པོ་+་གཅུང་པོ་
49. ་གཉེན་ཀི་+་གི་
50. ་གཞུང་དེའི་ཚོའི་+་དེ་
51. ་སེམས་ཙམ་པ་+་པའི་
52. ་མ་ཟེ་ནས།+་མ་རེད་ཟེར་ནས།
53. ་དུས་སུ་+་འདུག་སེ་(7)
54. ་བཤད་རྒྱབ་པ་+་བརྒྱབ་
55. ་ལེན་ཀི་+་གི་
56. (19:33)

2023-03-30 06:32 UTC, Jamtsul requested changes
stt003-06-སྐར་མ་19:33 ནས་བཅོས།

1. ་རང་རྒྱུ་ལ་+་རང་གི་རྒྱུ་ལ་
2. ་རེད་ཟེ་ཡ་དེ་ཀི་ལས་འབྲས་ཟེར་ཡ་དེ་ཀི་སྐད་ཆ་བཤད་པ་རེད་མཁྱེན་+་རེད་ཟེར་ཡ་དེ་གས་ལས་འབྲས་ཟེར་ཡ་དེ་གའི་སྐད་ཆ་བཤད་པ་རེད། མཁྱེན་
3. ་ལྟོས་རྒྱུ་ཡིས་དབང་ལས་འབྲས་+་ལྟོས། རྒྱུ་ཡི་དབང་གིས་འབྲས་
4. ་ང་ཚོ་ཆོས་ཉིད་རིམ་པ་+་ང་ཚོས། ཆོས་ཉིད་ཀྱི་རིགས་པ་
5. ་ཞིག་ཀུན་+་ཞིག་གི་ཀུན་
6. ་ཆགས་བཞག་+་ཆག་བཞག་
7. ་ཡོད་པ་ཅེས་ནས་ང་ཚོའི་+་ཡོད་པ་ཟེར་བྱས་ནས་ང་ཚོས་
8. ་ཡ་ཀི་ལས་ཀ་+་གི་
9. ་རྒྱུའི་འབྲས་+་རྒྱུས་
10. ་ཞེ་བོའི་+་ཞེ་བོ་
11. ་ཧོབ་དུ་ལྟོས་ན་ཡིན་ན་ད་ཧོབ་དུ་སྒང་ལ་ལྟོས་བ་+ཧོབ་དེ་ཁ་ལ་བལྟས་པ་ཡིན་ན་རེད་ད། ཧོབ་དེ་ཁ་ལ་བལྟས་པ་
12. རྗས་རྡུལ་+རྫས་
13. ་ཁོ་རང་དུས་སུ་ཡ་+་ཁོ་རང་འདུག་སེ་ཡར་
14. ་སེལ་ཀི་སེལ་ཀི་+་གི་
15. ་གསར་བ་ཞིག་སླེབ་+་་གསར་པ་ཞིག་སླེབས་
16. དུས་སུ་བྱས་ནས་ཁོ་མཚར་+འདུག་སེ་བྱས་ནས་ཁོ་འཚར་
17. ་དེའི་ཚོའི་+་དེ་
18. ་ཡོང་བ་ཤ་+་ཡོང་བསྡད་པ་ཤ་
19. ་ཙམ་ཀི་+་གི་
20. ་སྡུག་ད་བདེ་+་སྡུག་དང་། བདེ་
21. ་སྡུག་སྐད་+་སྡུག་གི་སྐད་
22. ་ཤེས་ད་ཚོར་+་ཤེས་དང་ཚོར་
23. ་དེ་ཀ་ལ་+་དེ་ག་ལ་(2)
24. ་མི་ཅག་ལོག་+་མི་གསུམ་ཆ་ལོ་
25. ་ཅག་ལོག་+་ཆ་ལོ་
26. ་ཡ་ཀི་+་གི་(19)
27. རེད་བས་+་པས་
28. དམིགས་གསལ་དམིགས་+དམིགས་སའི། དམིགས་
29. ་རྐྱེན་ཟོལ་+་རྐྱེན་གི་ཟོལ་
30. ་འགྲོ་ཀི་+་གི་(6)
31. ་སྔར་རྒྱུད་གཅིག་+་རྒྱུ་
32. ་གཅིག་གི་ནུས་པ་+་གིས་
33. ་བཞག་ད་དེ་+་བཞག་པ། ད། དེ་
34. ཤེས་བ་+་པ་
35. ་ཟེ་ཅེས་ནས་+་ཟེར་བྱས་ནས་
36. ་ཐར་འགྱུར་+་ཐལ་
37. ་བྱས་བ་+་པ་(4)
38. ་དེ་སྒང་ལ་+་དེའི་
39. ་པར་ཀི་+་གི་
40. ་གསར་བ་ཞིག་སྒྲུབ་ནས།+་གསར་པ་ཞིག་བསྒྲུབས་ནས།
41. དེ་ནང་གསེས་+་དེའི་
42. ་འདས་ཀི་འདི་+་ཀིས་
43. ་པའོ་ཟེ་གསུངས་+་ཟེར་
44. ་བསྔལ་ཀི་+་གི་(4)
45. ་ང་ཚོའི་འདི་ཚོར་བ་+་་ང་ཚོས་འདིར་ཚོར་བ་
46. ་བསྔལ་ད་+་དང་
47. ་རྩིས་+་བརྩི་
48. ་ཚོགས་ལ་+་་ཚོགས་པ་ལ་
49. ་ཅན་ཀི་+་གི་(3)
50. ་ཟེར་ཀི་+་གི་(11)
51. འདས་ཀི་དེ་ལ་+་ཀིས་
52. ་ཏིང་ངེས་འཛིན་+་ངེ་
53. ་མ་ལོག་གི་+་མ་ལོ་གིས་
54. ་ཚང་མ་ལོག་+་ལོ་(6)
55. ་དེའི་ལ་ལྟོས་ན་+་དེ་
56. ་ངན་འགྲོ་ཟེ་ཅེས་ནས་+་ངན་འགྲོ་ཟེར་བྱས་ནས་
57. ་ངན་འགྲོ་ཅེས་ནས་+་ངན་འགྲོ་ཟེར་བྱས་ནས་
58. ་ཤེས་རབ་ཀྱིས་ནས།+་ཤེས་རབ་ཟེར་བྱས་ནས།
59. ་སྒྲུབ་བྱ་+་བསྒྲུབ་(2)
60. ་སྒྲུབ་བཞག་པ།+་བསྒྲུབས་
61. ་གསུམ་བཞག་ནས་མཁྱེན་སོང་ང་།+་གསུམ་བཞག མཁྱེན་སོང་ང་། ད། ལས་གསུམ་བཞག་ནས།
62. ་བསྒྲུབ་མཁན་ཀི་+་སྒྲུབ་མཁན་གི་
63. ག་འདྲ་ཟེ་ཡོད་+ག་འདྲ་ཞིག་ཡོད་
64. ་ང་ཚོའི་བཤད་+་ཚོས་
65. ་ཧམ་པ་ཅན་+་ཧམ་པ་བྱེད་བསྡད་ངེ་
66. ་ཡུལ་ཡུལ་ཡིད་དུ་+་ཡིད་ལུས་ཡིད་དུ་
67. ་བཙམ་+་བཙན་
68. ་དེ་ཡོང་+་དེ་གས་དེ་ཡོང་
69. ་རྒྱབ་ཀྱི་ཕྱོགས་+་ཀྱིས་
70. ་མེད་གྲང་བསམ་ཀི།+་མེད་འགྲོ་བསམ་གི།
71. ་མིན་གྲང་བསམ་ཀི་+་མེད་འགྲོ་བསམ་གི།(4)
72. ་གནོད་སེམས་ཀི་ཨེ་ནས་+་ཀིས་
73. ་འདི་ལོག་ལྟ་+་འདིའི་
74. ཁྱད་ཀེ་+་གེ་
75. ་མ་རེ་བསམ་+་རེད་
76. ་དེའི་ཕལ་ཆེར་+་དེ་
77. ་དེ་ཚོའི་ད་ག་ནང་+་དེ་ཚོའི། དེ་ག་ནང་
78. (33:04)

2023-03-30 18:54 UTC, Jamtsul requested changes
stt003-06-སྐར་མ་33:04ནས་བཅོས་ཡོད།

1. ་གས་དེའི་སླེབ་+་དེ་
2. ་པ་ར་ཅིག་གི་+་པ་འདྲ་བོ་ཅིག་གིས་
3. ་འགལ་ཀི་+་གི་
4. ་ཕལ་ཆེར་སླེབ་བསྡད་+་སླེབས་
5. ་ཁུངས་རྩིས་བ་+་ཁུངས་བརྩིས་པ་
6. ་མི་གཅིག་བསག་བཞག་+་བསད་
7. ་གཅོད་ངེ་ཀེ་+་གཅོད་ངེ་ནི་གེ་
8. ་པ་རེད་ཅིག་+་པ་འདྲ་བོ་ཅིག་
9. ་བསྡད་ངེ་ལོག་+་བསྡད་པའི་ལོག་
10. ་དེ་ཀི་སྲོག་གཅོད་+་གིས་
11. འདྲ་ཀི་+་གི་
12. ་མེད་བ་+་པ་
13. ་མ་ཆེ།+་ཆེས་
14. གཞན་ང་ཚོའི་ལམ་+་ཚོས་
15. ་མིན་གྲང་བསམ་ཀི།+་མིན་འགྲོ་བསམ་དྲན་གི།
16. ་ལ་ལོག་ལྟ་རེད་ལ།+་ལ་ལོག་ལྟ་ལ་འགྲེལ་ན།
17. ་ཚང་མ་ལོག་གོ་+་ཚང་མ་ལོ་ལ་གོ་
18. ་ལ་ཡི་ལོག་+་ཡང་
19. ་དག་དག་+་ཏག་ཏག་
20. ་རྒྱུ་ཀི་+་གི་
21. ་ལས་དེ་ཀི་+་གིས་
22. ་གིས་དེ་གནས་+་དེའི་
23. ་སྲིད་རེད།+་སྲིད་པ་རེད།
24. ལས་དེ་ཀི་འཕྲད་དུ།+་ལས་དེ་གིས་འཕྲལ་དུ།
25. ་མཐུ་ཆེན་སྒྲུབ་ཡ་ཀི་+་་མཐུ་ཆེན་འགྲུབ་ཡ་གི་
26. ་གསལ་དེ་གས་དེའི་+་བསལ་དེ་གས་དེ་
27. ་ནང་ལོགས།།བསོད་+་ནང་ལ། བསོད་
28. རྒྱུའི་དང་འབྲས་བུའི་+་རྒྱུ་དང་
29. ་ནམས་མཁའི་མཐས་+་ནམ་མཁའི་མཐར་
30. ་གས་དེའི་ཚང་མ་ལོག་+་གས་དེ་ཚང་མ་ལོ་
31. ་ཚིག་དོན་བཀྲལ་བ་+་ཚིག་མར་ཏོག་ཟི་བཀྲལ་བ་
32. ་འབྲེལ་ཀི་ཆོས་དེའི་མཐོང་+་འབྲེལ་གི་ཆོས་དེ་མཐོང་
33. གཙོ་བོ་ད་དེ་ཐོག་+་དེའི་
34. སྔར་ཀི་+་གི་
35. ་ནང་ལོག་+་ལོགས་
36. (ཡོངས་རྫོགས་བཅོས་ཟིན།)

2023-04-20 06:19 UTC, Jamtsul requested changes
stt003-06 འགོ་ནས་བསྐྱར་བཅོས་གཉིས་པ་སོང་ཡོད།

1.་ཟོར་འདྲ་བོ་+་ཟོལ་(8)
2. འདུས་སེ་+་འདུག་(8)
3. ་བཞན་+་གཞན་
4. ་ན་ཡ་+་ནས་ཡར་
5. ནུན་ཏལ་+་ན་ལེན་ཊ་ལ་
6. ་ལས་འདུག་ངའི་+་ལའང་འདུག་ངས་
7. ཟ་ཟས་+་ཟ་སའི་
8. ་ཞིག་གི་བྱུང་+་གིས་
9. ་སྐྱེད་བྱ་+་བསྐྱེད་
10. རྒྱུའི་འབྲས་བུའི་+་རྒྱུ་འབྲས་བུའི་
11. ད་ཨ་ལྟ་དངོས་པོ་ཡིན་ན།+ད་གང་ལྟར་དངོས་པོ་ཡིན་ན།
12. ་པའི་ཁྱབ་+་པས་(3)
13. ་བརྙེད་+་བརྙེས་
14. ་ལས་ཀི་བྱུང་+་ཀིས་
15. ་བའི་ཁྱབ་+་བས་
16. པའི་མ་ཁྱབ་+་པས་
17. ་འདས་ཀི་དེ་+་ཀིས་
18. ་མིན་གྲང་+་མེད་འགྲོ་
19. ་འཕྲད་དུ+་འཕྲལ་
20. ་རྗེས་དེ་+་གཞུག་གུ་དེ་
21. ་འཇུག་བསྡོག་+་མཇུག་ལྡོག་
22. stt003-06 བསྐྱར་བཅོས་གཉིས་པ་གྲུབ་ཡོད།

2023-04-26 07:57 UTC, Jamtsul approved these changes
Lhundup22: stt003-06 བསྐྱར་བཅོས་གཉིས་སོང་ཡོད། སྐར་མ་40:58
stt003-07 བསྐྱར་བཅོས་གཅིག་སོང་ཡོད། སྐར་མ་46:17=87:15ཁྱོན་བསྡོམས་ཡིན།

2023-05-11 06:34 UTC, Rangdol3101 requested changes
stt003-08འགོ་ནས་ནོར་བཅོས་བྱས་ཡོད།

1. རེད་བཞག+་རེད་ཤག(༢༢)
2. གཡས་གཡོན་ལ་+གཡས་གཡོན་ནས་
3. མཁྱེན་སོང་ང་། +ཤེས་སོང་ང་།
4. བདེན་པ་+བདེན་པར་
5. རྒྱབ་ཀི་ཡོད+བརྒྱབ་ཡོད
6. དཔེ་ག་རེ་ཟེར་དགོས་+འུ། ད་ག་རེ་ཟེར་དགོས་
7. ཡར་རྒྱས་ཀིས་+ཡར་རྒྱས་ཀི
8. ་ཡོད་མེད་དེ། བསམ་བློ་བཏང་གི་+ཡོད་མེད་དེ་བསམ་བློ་གཏང་གི
9. བྱས་ཀྱིས།+བྱས་བྱས
10. རེད་ཟེར་ལབ་ན།+རེད་ཟེ་ལབ་ན
11. འདྲ་ཉམས་ཀི་+འདྲ་མཉམ་གི་
12. མ་ཁེ་སུའི་རིང་ལུགས+མར་ཁེ་སི་རིང་ལུགས
13. མི་རིགས་ཐོབ་ཐང་དགོས་ཀི་ཡོད་ཟེར་བྱས་ནས། +མི་རིགས་ཀི་ཐོབ་ཐང་དགོས་ཀི་ཡོད་བྱས་ནས
14. ཟེར་ལབ་ན+ཟེ་ལབ་ན
15. བྷོ་རོ་ནའི་ཡ+བྷོ་ལོ་ནའི་ཡ
16. བྱ་དཀའ་གནང+བྱ་དགའ་གནང
17.  སྤུ་གསོབ་གསོབ་+སྤུ་སོབ་སོབ་
18. བུ་གུ་ཚོོས+བུ་གུ་ཚོས
19. ན་ལེནྡྲའི་+ནཱ་ལེནྡྲའི
20. བཙུག་པ་རེད།+བཙུགས་པ་རེད
21. བསླབ་པ་གྲས་པ་རེད།+བསླབ་པ་བགྲེས་པ་རེད
22. གྲགས་ག་+དྲག་ག(2)
23. ཡིན་ན་མིན་ནའང་། འུ། རྒྱ་ནག་+ཡིན་ན་མིན་ནའང་། ད། རྒྱ་ནག་
24. རིགས་པའི་དཔྱད་པ་བྱེད་+རིགས་པས་དཔྱད་པ་བྱེད(3)
25. རྩལ་འདོད་བྱེད་ས+རྩལ་འདོན་བྱེད་ས
26. ཡང་དགོས།+ཡང་སྒོས།
27. དེ་ནང་ཚན་ནས།+དེའི་ནང་ཚན་ནས
28. ཤེས་པ་གཅིག་བྱས།+དེ་ཤེས་པ་གཅིག་བྱས
29. ཆབ་གཅིག+ཆབས་ཅིག(2)
30. ཧུད་ཐག་པ་ཐག+ཧུར་ཐག་པ་ཐག
31. རིགས་གཞུང་། +རིག་གཞུང་།
32. 12:15

2023-05-25 03:13 UTC, closed without merging